### ISSUE TITLE
undefined method `submittedProblemIndex=' 

### ISSUE THREAD

**Issue by pathikrit** [sh19910711/git-contest#43]
I tried to submit in contest 626 on CodeForces. I got this error and it did not submit...

```
Submitting target/submissions/_626C.scala ...
@start: submit
@submit: logging in...
@submit: login ok
@submit: doing...
/Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/contest/driver/codeforces_driver.rb:111:in `block in submit_ext': undefined method `submittedProblemIndex=' for nil:NilClass (NoMethodError)
        from (eval):23:in `form_with'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/contest/driver/codeforces_driver.rb:110:in `submit_ext'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/contest/driver/base.rb:137:in `submit'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/git/contest/command_line/sub_commands/submit_command.rb:166:in `run'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/git/contest/command_line/main_command.rb:34:in `call_subcommand'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/git/contest/command_line/main_command.rb:21:in `run'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/bin/git-contest:15:in `<top (required)>'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/bin/git-contest:23:in `load'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/bin/git-contest:23:in `<main>'
```

**Comment by pathikrit** [comment]
I vierified it does not work for other contest too:

```
Submitting target/submissions/_625A.scala ...
@start: submit
@submit: logging in...
@submit: login ok
@submit: doing...
/Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/contest/driver/codeforces_driver.rb:111:in `block in submit_ext': undefined method `submittedProblemIndex=' for nil:NilClass (NoMethodError)
        from (eval):23:in `form_with'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/contest/driver/codeforces_driver.rb:110:in `submit_ext'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/contest/driver/base.rb:137:in `submit'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/git/contest/command_line/sub_commands/submit_command.rb:166:in `run'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/git/contest/command_line/main_command.rb:34:in `call_subcommand'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/lib/git/contest/command_line/main_command.rb:21:in `run'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/git-contest-0.2.6/bin/git-contest:15:in `<top (required)>'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/bin/git-contest:23:in `load'
        from /Users/pbhowmick/.rbenv/versions/2.2.3/bin/git-contest:23:in `<main>'
```

This same code used to work till last week. Did the CodeForces API or website change?

**Comment by pathikrit** [comment]
@sh19910711 : Hi, this error is still happening on different machines too. Any idea? Did CodeForces change the site?

**Comment by pathikrit** [comment]
My bad, I had an empty config.yml file. Maybe a better error message :)

**Comment by sh19910711** [comment]
@pathikrit Sorry for the late reply. I had no time to investigate the issue. But yeah, I think so, too. We could improve the error message.
